

export const VOTING_MOTIVE = "Your vote has the potential to make a significant difference. Your vote has the potential to make a significant difference.  If people do not vote, the same party or people will be in power for another round. Finally, if the country is left with a bad administration, it is the people's fault for voting incorrectly or not at all."




export const DUMMY_TEXT = "The Indian government has made it possible for voters to cast their ballots even if they are unsatisfied with any of the candidates. NOTA stands for None of the Above, and it's a crucial vote for individuals who aren't satisfied with any of the candidates. NOTA voting means that none of the candidates are suitable. NOTA votes are counted, but if the majority of the votes are NOTA, the party with the next largest majority will be elected.The Indian government has made it possible for voters to cast their ballots even if they are unsatisfied with any of the candidates. NOTA stands for None of the Above, and it's a crucial vote for individuals who aren't satisfied with any of the candidates. NOTA voting means that none of the candidates are suitable. NOTA votes are counted, but if the majority of the votes are NOTA, the party with the next largest majority will be elected.The Indian government has made it possible for voters to cast their ballots even if they are unsatisfied with any of the candidates. NOTA stands for None of the Above, and it's a crucial vote for individuals who aren't satisfied with any of the candidates. NOTA voting means that none of the candidates are suitable. NOTA votes are counted, but if the majority of the votes are NOTA, the party with the next largest majority will be elected.The Indian government has made it possible for voters to cast their ballots even if they are unsatisfied with any of the candidates. NOTA stands for None of the Above, and it's a crucial vote for individuals who aren't satisfied with any of the candidates. NOTA voting means that none of the candidates are suitable. NOTA votes are counted, but if the majority of the votes are NOTA, the party with the next largest majority will be elected.The Indian government has made it possible for voters to cast their ballots even if they are unsatisfied with any of the candidates. NOTA stands for None of the Above, and it's a crucial vote for individuals who aren't satisfied with any of the candidates. NOTA voting means that none of the candidates are suitable. NOTA votes are counted, but if the majority of the votes are NOTA, the party with the next largest majority will be elected."

export const mainColor = '0d102f'